import type { ProofDerivation } from './DetailHint';

type Pair = readonly [string, string];

function derive(
  formula: string,
  symbols: readonly Pair[],
  steps: readonly Pair[],
  verifier: string,
  validity: string,
  assumptions: string,
): ProofDerivation {
  return {
    formula,
    symbols: symbols.map(([label, value]) => ({ label, value })),
    steps: steps.map(([expression, explanation]) => ({ expression, explanation })),
    verifier,
    validity,
    assumptions,
  };
}

export const derivations = {
  worldState: derive(
    'root(Σ) = H("acvm-state" ∥ root(A) ∥ root(C) ∥ root(T) ∥ root(R) ∥ root(P))',
    [['Σ', '某个已确认高度的完整 ACVM 世界状态。'], ['A/C/T/R/P', '身份、合约、任务、回执、证明五棵子状态树。'], ['H', '带域分离标签的抗碰撞哈希函数。']],
    [['encode(Σ)=tag∥len(A)∥A∥…∥len(P)∥P', '先固定字段顺序、类型标签和长度，排除两种结构编码成同一字节串。'], ['rᵢ=MerkleRoot(canonical(substateᵢ))', '每棵子树独立计算承诺，因此单条记录可用 O(log n) 包含路径核验。'], ['root(Σ)=H("acvm-state"∥r₁∥…∥r₅)', '最后把五个子根绑定成区块状态承诺；任一叶子变化都会沿路径传播到根。']],
    'RecomputeRoot(Σ, canonicalEncoding) = header.stateRoot',
    '规范编码、叶子顺序和哈希算法完全一致，且哈希未出现可行碰撞时，根相同才表示状态承诺相同。',
    '所有节点使用同一协议版本；哈希满足二次原像与碰撞抗性。',
  ),
  canonicalEncoding: derive(
    'Enc(x₁,…,xₙ)=domain ∥ type₁ ∥ len₁ ∥ bytes₁ ∥ … ∥ typeₙ ∥ lenₙ ∥ bytesₙ',
    [['domain', '对象类型的域分离标签，例如 task、receipt 或 contract。'], ['typeᵢ/lenᵢ', '字段类型和字节长度。'], ['bytesᵢ', '字段按协议规定得到的唯一字节表示。']],
    [['Sort(fields)=protocol order', '先按协议声明顺序组织字段，不能依赖对象遍历或本地文件系统顺序。'], ['Prefix(typeᵢ,lenᵢ)', '为每段加入类型和长度，避免 ab∥c 与 a∥bc 之类的拼接歧义。'], ['Decode(Enc(x))=x', '唯一可解码性保证不同实现面对同一对象得到同一输入字节。']],
    'Decode(Enc(x)) = x ∧ ∀x≠y: Enc(x)≠Enc(y)',
    '编码必须是单射；只有先满足这一点，后续签名和哈希才能绑定明确的数据结构。',
    '文本标准化、整数端序、浮点限制、路径分隔符和可选字段规则均已写入协议。',
  ),
  hashBinding: derive(
    'c = H(domain ∥ Enc(m));  Open(c,m) := [H(domain ∥ Enc(m)) = c]',
    [['m', '需要承诺的消息、文件或结果。'], ['c', '固定长度哈希承诺。'], ['domain', '防止同一字节串跨对象类型复用的标签。']],
    [['b=domain∥Enc(m)', '先把语义明确地编码成唯一字节串。'], ['c=H(b)', '用哈希把任意长度内容压缩成固定长度承诺。'], ['Open(c,m′)', '公开 m′ 后重算；若 m′ 被改动，除非找到二次原像，否则不会匹配 c。']],
    'H(domain ∥ Enc(m′)) = c',
    '校验通过只能证明“打开的内容与原承诺一致”，不能单独证明内容来自真实世界。',
    '哈希满足二次原像与碰撞抗性；真实性另由签名、预言机或环境证明提供。',
  ),
  hashChain: derive(
    'Cᵢ = H("stage" ∥ taskId ∥ i ∥ Cᵢ₋₁ ∥ Δᵢ ∥ ruleHash)',
    [['Cᵢ', '第 i 阶段结束后的状态承诺。'], ['Δᵢ', '本阶段新增的输入、动作、输出与回执摘要。'], ['ruleHash', '本任务冻结的状态转换和验收规则版本。']],
    [['C₀=H(taskId∥inputRoot∥ruleHash)', '起点同时冻结任务、初始输入和规则。'], ['Cᵢ←H(Cᵢ₋₁∥Δᵢ∥…)', '每一步显式引用上一承诺，删除、插入或换序都会改变后续全部承诺。'], ['Cₙ commits (Δ₁,…,Δₙ)', '因此一个固定长度终点可以承诺整条有序工作轨迹。']],
    'Recompute(C₀, Δ₁…Δₙ, ruleHash) = Cₙ',
    '阶段编号、前序承诺、任务 ID 和规则版本均匹配时，轨迹连续性成立。',
    '哈希安全且每个阶段增量使用规范编码；数据真实性仍由各阶段签名和证明保证。',
  ),
  identityAuthorization: derive(
    'Authorize(I,cap,t)=Dsig(pk,H(I)) ∧ VerifyCap(cap,pk,scope,t)=1 ∧ ¬Revoked(cap,t)',
    [['I', '带 taskId、参数、nonce、期限和验收条件的调用意图。'], ['cap', '签发给主体密钥的能力凭证。'], ['scope/t', '本次动作范围与链上时间。']],
    [['Dsig(pk,H(I))', '验签先证明意图由对应私钥持有者授权，参数被签名绑定。'], ['VerifyCap(cap,pk,scope,t)', '再检查能力链从签发者到调用者连续、权限没有放大且尚未过期。'], ['¬Revoked(cap,t)', '最后读取已确认撤销状态，排除已失效身份或能力。']],
    'SigVerify(pk,H(I),σ)=1 ∧ scope(I)⊆scope(cap) ∧ t≤expiry ∧ cap∉Revoked',
    '签名、能力范围、有效期、撤销状态四项同时通过才授权；任何一项失败都不启动 Worker。',
    '签名方案不可伪造；撤销根足够新；链上时间与能力策略有明确语义。',
  ),
  signedIntent: derive(
    'd = H("intent"∥caller∥taskId∥paramsRoot∥budget∥SLA∥nonce∥expiry);  σ=Sign(sk,d)',
    [['d', '调用意图的规范摘要。'], ['nonce', '调用方作用域内唯一的随机数或递增序号。'], ['σ', '调用方对摘要的数字签名。']],
    [['Freeze fields', '先把目标、预算、输入承诺、验收口径和期限全部冻结到摘要。'], ['Sign(sk,d)', '私钥签名把责任主体与完整意图绑定，第三方不能只替换某个参数。'], ['Check nonce & expiry', '状态机再检查 nonce 未使用且未过期，阻断复制旧签名的重放。']],
    'Verify(pk,d,σ)=1 ∧ now≤expiry ∧ nonce∉Used[caller]',
    '验签通过且 nonce 首次出现时，才证明这是一个当前有效、不可被改写的真实调用。',
    '私钥未泄漏；随机数唯一或序号严格单调；链上使用规范时间源。',
  ),
  contractTree: derive(
    'leafᵢ=H("file"∥pathᵢ∥lenᵢ∥H(bytesᵢ));  contractRoot=Merkle(sort_path(leafᵢ))',
    [['pathᵢ', '合约业务目录中的规范相对路径。'], ['bytesᵢ', 'contract、schema、worker、validator 或 settle 文件内容。'], ['contractRoot', '部署版本的内容寻址根。']],
    [['Normalize(pathᵢ)', '统一分隔符、大小写规则并拒绝越界路径，保证文件身份唯一。'], ['leafᵢ=H(pathᵢ∥lenᵢ∥H(bytesᵢ))', '路径、长度和内容同时进入叶子；改名与改内容都会改变叶子。'], ['Merkle(sort_path(leaves))', '按规范路径排序构树，让任何平台得到同一根并支持局部包含证明。']],
    'MerkleVerify(contractRoot, leafᵢ, pathProofᵢ)=1 ∧ runtime.contractRoot=contractRoot',
    'Worker、Validator 与结算必须引用同一个已部署根，才能证明没有在任务中途换代码。',
    '只提交业务目录；工具、网络和文件系统能力由 ACVM/a3s-box 平台策略固定并另行度量。',
  ),
  schemaValidation: derive(
    'ValidSchema(x,S) := Parse(Enc(x))=x ∧ TypeCheck(x,S)=1 ∧ Canon(x)=Enc(x)',
    [['x', '某阶段输入、结果或裁决文件。'], ['S', '部署时进入 contractRoot 的 Schema 版本。'], ['Canon', '协议唯一的规范序列化函数。']],
    [['Parse', '先拒绝语法错误、未知字段和重复键，避免不同解析器给出不同对象。'], ['TypeCheck', '检查类型、范围、必填项和跨字段约束。'], ['Canon', '把对象重新规范编码并与原输入比较，拒绝多种等价表示。']],
    'Parse(Enc(x))=x ∧ Validate_S(x)=1 ∧ S.root⊆contractRoot',
    '文件同时满足可解析、类型约束和版本绑定时，才允许进入下一阶段。',
    'Schema 语言必须是确定性的；不能在验证时调用不稳定的外部网络或本地时钟。',
  ),
  taskState: derive(
    'Tₜ₊₁ = δ(Tₜ,event) if Guard(Tₜ,event)=1; otherwise Tₜ₊₁=Tₜ',
    [['Tₜ', '任务当前阶段、责任方、截止时间和前序根。'], ['event', '部署、执行、验收、挑战或结算事件。'], ['δ/Guard', '确定性状态转换函数及其前置条件。']],
    [['Enumerate states', '先列出 pending、running、verified、settled、failed 等有限状态。'], ['Guard(T,event)', '为每条边写明授权、前序根、回执与时间条件；未列出的边一律拒绝。'], ['δ(T,event)', '条件通过后只产生一个下一状态，因此同一输入不会出现两个解释。']],
    'Guard(Tₜ,event)=1 ∧ δ is deterministic ∧ prevRoot(event)=root(Tₜ)',
    '状态、事件和前序根相同的节点必须算出相同下一状态；条件失败时保持原状态。',
    '所有影响共识的输入都已显式进入 event；外部事实只能通过已验证回执进入。',
  ),
  deterministicState: derive(
    'Σₜ₊₁ = Φ(Σₜ, OrderedTxₜ, VerifiedReceiptsₜ)',
    [['Σₜ', '转换前已最终确认的状态。'], ['OrderedTxₜ', '共识给出的唯一交易顺序。'], ['Φ', '不读取本地随机数、浮点差异或未证明外部状态的确定性函数。']],
    [['Same root', '节点先确认自己持有同一个前序 stateRoot。'], ['Same ordered inputs', '共识层固定交易和回执顺序，并逐项验证签名、证明与 nonce。'], ['Pure transition', 'Φ 只对显式输入做确定性运算，于是相同输入必然得到相同输出根。']],
    'root(Φ(Σ,x,r)) is identical on every honest validator',
    '前序根、输入顺序、验证规则和协议版本完全一致时，状态复制机保持一致。',
    '实现不存在未定义行为；整数溢出、编码、Gas 和失败语义都由协议固定。',
  ),
  gasBound: derive(
    'Gas(tx)=Σⱼ cost(opⱼ)+α·bytesRead+β·bytesWritten ≤ GasLimit',
    [['opⱼ', '第 j 个确定性链上操作。'], ['α/β', '协议固定的读写单价。'], ['GasLimit', '调用者愿意支付且区块允许的资源上界。']],
    [['Assign cost', '给每类指令和存储操作设定与最坏资源消耗相关的整数成本。'], ['Accumulate before commit', '执行中单调扣减剩余 Gas，耗尽立即进入失败分支。'], ['Bound block work', '区块 Gas 上限把所有交易成本之和限制在节点可处理范围。']],
    'GasUsed≤GasLimit ∧ Σtx GasUsed(tx)≤BlockGasLimit',
    '所有实现使用同一计价表且越界原子回滚时，单区块确定性计算量存在硬上界。',
    '计价表需随硬件和拒绝服务风险校准；链下 CPU/GPU 通过资源租约单独计量。',
  ),
  atomicRevert: derive(
    'Exec(Σ,tx)=(ok,Σ′,r);  Commit = ok ? Σ′ : Σ',
    [['Σ', '调用前状态快照。'], ['Σ′', '隔离执行得到的候选写集。'], ['ok', '权限、Gas、证明和业务谓词的合取结果。']],
    [['Journal writes', '执行期间写入临时日志或持久化数据结构的新版本，不覆盖已确认状态。'], ['Evaluate ok', '执行结束统一检查全部必须条件。'], ['Atomic choose', 'ok=1 才提交候选根；ok=0 丢弃写集并保留原根。']],
    'ok=0 ⇒ root(Commit)=root(Σ);  ok=1 ⇒ root(Commit)=root(Σ′)',
    '提交点是原子的，而且失败分支不能把部分业务写入泄漏到正式状态。',
    '底层存储支持事务、写前日志或持久化 Merkle 结构；失败回执与业务状态分开记录。',
  ),
  receiptMerkle: derive(
    'leafᵢ=H("receipt"∥taskId∥stage∥actor∥payloadRoot∥σᵢ);  R=Merkle(leaf₁…leafₘ)',
    [['leafᵢ', '一条已签名 Worker、Validator、工具或安全回执摘要。'], ['R', '该批回执集合根。'], ['pathᵢ', '从叶子到根的兄弟哈希序列。']],
    [['Bind receipt', '任务、阶段、责任主体、结果承诺和签名进入同一叶子。'], ['Build tree', '两两哈希得到固定长度根；m 条记录只需一个根进入共识状态。'], ['Verify inclusion', '审计时提供正文和约 log₂m 个兄弟哈希即可重算 R。']],
    'SigVerify(actor,leafPayload,σᵢ)=1 ∧ MerkleVerify(R,leafᵢ,pathᵢ)=1',
    '验签证明责任来源，包含路径证明该回执已被指定区块承诺；两项缺一不可。',
    '叶子采用规范编码与域分离；可用性层需保证回执正文能够取回。',
  ),
  receiptBundle: derive(
    'ρ={rW,rV,rTool,rEnv};  bundleRoot=Merkle(H(Enc(r)) for r∈ρ)',
    [['rW/rV', 'Worker 执行回执与 Validator 裁决回执。'], ['rTool/rEnv', '外部工具调用及运行环境证据。'], ['bundleRoot', '本次任务证据包的集合承诺。']],
    [['Same task binding', '每条回执先检查 taskId、contractRoot、inputRoot 和 stage 相同。'], ['Independent signatures', '分别验证各证据生产者的签名或环境证明。'], ['Aggregate commitment', '通过的回执按类型和主体排序进入 Merkle 树，防止遗漏或换序。']],
    '∀r∈ρ: Bind(r,taskId,contractRoot,inputRoot)=1 ∧ Verify(r)=1',
    '证据包中所有必需角色齐全、绑定字段一致且各自验证通过时，才可供状态转换使用。',
    '协议明确每种任务所需的最小回执集合；可选回执不能替代必需回执。',
  ),
  workerExecution: derive(
    '(y,τ)=Exec(codeRoot,x;env);  cᵧ=H(y);  cτ=Merkle(τ)',
    [['codeRoot', '部署时冻结的 Worker 代码目录根。'], ['x/y', '规范输入文件与结果文件。'], ['τ', '文件、工具、网络代理和运行时事件组成的轨迹。']],
    [['Materialize x', 'ACVM 把签名意图转成通过 Schema 的任务文件，并记录 inputRoot。'], ['Run isolated codeRoot', 'a3s-box 在平台固定边界内启动已度量 Worker，收集资源与工具事件。'], ['Seal outputs', '输出、轨迹、环境度量和前序根一起哈希并由 Worker 身份签名。']],
    'VerifyExec(π, codeRoot,inputRoot,cᵧ,cτ,envMeasure)=1',
    '证明或可复算轨迹与部署代码、输入、输出和环境度量全部一致时，执行证据有效。',
    '执行真实性取决于所选证明机制；单独的 Worker 签名只能归责，不能排除 Worker 作恶。',
  ),
  validatorDecision: derive(
    'bᵢ=P(ruleHash,inputRoot,outputRoot,evidence)=1;  Accept ⇔ Σᵢ wᵢbᵢ ≥ θ',
    [['P', '部署时冻结的确定性验收谓词。'], ['bᵢ', '第 i 个独立 Validator 的签名裁决。'], ['θ', '合约规定的权重或数量阈值。']],
    [['Freeze predicate', '任务开始前把规则版本和阈值写入 contractRoot，避免结果出来后改口径。'], ['Evaluate evidence', 'Validator 对相同输入根、输出根和证据运行 P，给出接受或带原因的拒绝。'], ['Threshold decision', '链上验签、去重主体并累计权重；达到 θ 才进入可结算状态。']],
    'Distinct(validators) ∧ ∀accepted i: SigVerifyᵢ=1 ∧ Σwᵢbᵢ≥θ',
    '裁决主体独立、签名有效、规则版本一致且达到阈值时，验收结果成立。',
    '阈值只降低串谋概率，不自动保证谓词正确；高风险任务需可挑战证据或密码学证明。',
  ),
  proofSoundness: derive(
    'Completeness: R(x,w)=1 ⇒ Pr[V(vk,x,π)=1]≥1−εc;  Soundness: R(x,w)=0 ⇒ Pr[V=1]≤εs',
    [['R(x,w)', '公共输入 x 与私密见证 w 应满足的执行关系。'], ['π', 'Prove(pk,x,w) 生成的证明。'], ['εc/εs', '完备性误差与可靠性错误上界。']],
    [['Arithmetize R', '把代码、输入输出承诺和状态约束转成证明系统可检查的关系。'], ['π←Prove(pk,x,w)', '执行者用真实轨迹作为见证生成证明；原始数据可以不公开。'], ['V(vk,x,π)', '共识节点只读取公共输入和验证密钥做快速验证。']],
    'V(vk,x,π)=1 ∧ vk.version=contract.vkVersion ∧ x binds taskId, roots, nonce',
    '验证通过表示“存在满足已冻结关系的见证”，其错误接受概率由 εs 限制。',
    '可信设置、实现安全、验证密钥治理和所证明关系本身均正确；证明不替代真实世界数据来源验证。',
  ),
  remoteAttestation: derive(
    'quote = Sign_AK(measurement ∥ config ∥ modelHash ∥ nonce ∥ outputRoot)',
    [['AK', '由硬件证明体系背书的证明密钥。'], ['measurement', '启动代码、固件和隔离环境的度量值。'], ['nonce', '验证方为本次任务给出的新鲜随机数。']],
    [['Challenge', '验证方先生成与 taskId 绑定的 nonce，旧 quote 因 nonce 不同不能复用。'], ['Measure & sign', '受保护环境度量代码、配置、模型和输出承诺，再由 AK 签名。'], ['Verify chain & policy', '链上或网关检查证书链、吊销、TCB 版本、白名单和 nonce。']],
    'CertChain(AK)=1 ∧ measurement∈Allowlist ∧ nonce=Expected ∧ SigVerify_AK(quote)=1',
    '证书链、软件度量、新鲜度和签名全部匹配时，才能证明指定环境产生了这份承诺。',
    '信任硬件根、厂商证书与侧信道防护；远程证明保证环境身份，不单独保证业务算法正确。',
  ),
  zkCapability: derive(
    'πcap = ZKProve{VC,sk,path : SigIssuer(VC)=1 ∧ subject(VC)=pk(sk) ∧ attr∈scope ∧ expiry≥t ∧ NonRevoked(path)}',
    [['VC/sk', '完整资质凭证与主体私钥，作为私密见证。'], ['scope/t', '公开的能力范围和验证时间。'], ['path', '凭证未出现在撤销集合中的证明路径。']],
    [['Verify issuer signature', '电路先验证可信签发者对完整凭证的签名。'], ['Prove predicates', '只证明岗位、牌照、评分等属性满足公开阈值，不公开原始值。'], ['Bind holder & revocation', '证明者同时证明持有主体密钥，并将撤销根和时间作为公共输入。']],
    'ZKVerify(vk,[scope,t,issuerRoot,revocationRoot,subjectCommitment],πcap)=1',
    '零知识验证通过时，资格、持有关系、有效期和未撤销同时成立，而隐藏属性不泄漏。',
    '证明电路正确表达凭证规则；撤销根和签发者集合已最终确认；证明系统满足零知识与可靠性。',
  ),
  pedersenCommitment: derive(
    'C = gᵐhʳ in group G;  Open(C,m,r) ⇔ gᵐhʳ=C',
    [['m', '身份标识或凭证摘要映射到群标量后的值。'], ['r', '每次承诺重新随机采样的盲化因子。'], ['g/h', '离散对数关系未知的两个群生成元。']],
    [['Sample r←$Zq', '均匀随机盲化让相同身份每次可产生不同承诺。'], ['C=gᵐhʳ', 'hʳ 将 m 隐藏；观察 C 的第三方无法区分候选 m。'], ['Open or prove', '需要时公开 m,r，或用零知识证明只展示关于 m 的必要谓词。']],
    'gᵐhʳ=C ∧ Range/credential predicates verified in ZK',
    '正确打开时内容一致；在不知道 log_g(h) 的前提下，攻击者不能为同一 C 找到两个不同消息打开。',
    'G 为安全素数阶群；r 不复用且使用密码学安全随机源；身份责任仍需签名或凭证绑定。',
  ),
  antiReplay: derive(
    'k=H("spent"∥chainId∥caller∥taskId∥nonce);  Accept ⇔ k∉Spentₜ;  Spentₜ₊₁=Spentₜ∪{k}',
    [['k', '跨链域、调用方、任务和 nonce 共同确定的消费键。'], ['Spentₜ', '在状态 t 已消费键的认证集合。'], ['nonce', '本授权作用域内唯一值。']],
    [['Domain-bind k', '加入 chainId 与调用方，避免同一签名跨链或跨主体复用。'], ['Check before effects', '任何转账、积分或状态推进前先查询认证集合。'], ['Monotonic insert', '成功状态转换与插入 k 原子提交；集合只增不减。']],
    'k∉Spentₜ ∧ Commit(effects,{k}) is atomic ∧ Spentₜ⊆Spentₜ₊₁',
    '首次出现的键可执行一次；之后所有重复提交命中 Spent 并保持业务状态不变。',
    '状态最终性不被回滚；跨链场景的 chainId 和消息域明确；插入与业务副作用处于同一原子事务。',
  ),
  booleanConjunction: derive(
    'Valid = a₁ ∧ a₂ ∧ … ∧ aₙ = ∏ᵢ aᵢ,  aᵢ∈{0,1}',
    [['aᵢ', '授权、签名、证明、验收、nonce 等一个必要检查。'], ['Valid', '是否允许状态推进的总判定。']],
    [['Map checks to bits', '每个检查必须给出确定性 0 或 1，不能使用“差不多通过”的模糊状态。'], ['Multiply / AND', '只要任一 aᵢ=0，乘积和逻辑与都为 0。'], ['Gate transition', 'Valid=1 才提交候选状态；Valid=0 走原子失败分支。']],
    'Valid=1 ⇔ ∀i,aᵢ=1',
    '所有列出的必要条件同时为真时整式才成立，任何一个失败都不能被多数成功项抵消。',
    '必要条件列表完整；每项检查在所有共识节点上有一致结果。',
  ),
  implication: derive(
    'a ⇒ b ≡ ¬a ∨ b;  violation ⇔ a=1 ∧ b=0',
    [['a', '触发某条协议义务的前件，例如 Verify(ρ)=1。'], ['b', '前件成立时必须执行的后件，例如提交指定状态。']],
    [['Truth cases', 'a=0 时规则未被触发；a=1 时必须继续检查 b。'], ['Detect violation', '唯一违规组合是前件为真而后件为假。'], ['Encode transition', '把违规组合映射为无效区块或状态转换拒绝。']],
    '¬(a=1 ∧ b=0)',
    '只有不存在“条件已经满足却没有履行后续规则”的情况，蕴含式才有效。',
    '前件和后件均被确定性编码，且没有协议外的隐式例外。',
  ),
  receiptVerification: derive(
    'Verify(ρ)=Bind ∧ Dsig ∧ MerkleInclusion ∧ ProofOK ∧ PredicateOK',
    [['Bind', 'taskId、contractRoot、前序根与输入输出承诺一致。'], ['Dsig', '回执生产者签名有效且身份获授权。'], ['ProofOK/PredicateOK', '执行证明与业务验收谓词均通过。']],
    [['Bind context', '先排除把别的任务、版本或状态上的合法回执搬过来使用。'], ['Verify authenticity', '验签、环境证明和包含路径分别核对来源、运行环境和链上记录。'], ['Evaluate result', '最后运行已冻结业务谓词；所有检查合取为一个布尔值。']],
    'Verify(ρ)=1 ⇔ ∧ checks =1',
    '回执只有在上下文、来源、包含性、执行有效性和业务结果全部通过时才可推动状态。',
    '验证密钥和规则版本受治理保护；外部数据的真实性由对应预言机证明单独承担。',
  ),
  bftFinality: derive(
    'N=3f+1, Q=2f+1;  |Q₁∩Q₂| ≥ 2Q−N = f+1',
    [['N', '共识验证节点总数。'], ['f', '协议保证范围内的最大拜占庭节点数。'], ['Q', '形成提交证书所需的签名数。']],
    [['Choose N,Q', '令 N=3f+1、Q=2f+1，使拜占庭节点不足以单独形成证书。'], ['Intersect quorums', '两个大小为 Q 的集合在 N 个节点中至少重叠 2Q−N=f+1 个节点。'], ['Use honest lock', '重叠至少 f+1，而作恶者最多 f，因此至少一个诚实节点不会为同一高度签冲突锁。']],
    'Commit(block) ⇔ |validVotes(block)|≥Q ∧ proposal extends lockedQC',
    '在故障不超过 f、诚实节点遵守锁定规则时，两个冲突区块不可能同时获得有效提交证书。',
    '网络最终同步用于活性；安全性还依赖签名不可伪造、节点密钥不被超额攻破。',
  ),
  folding: derive(
    'Uᵢ = Fold(Uᵢ₋₁, uᵢ; rᵢ),  and Sat(Uᵢ) ⇔ Sat(Uᵢ₋₁) ∧ Sat(uᵢ)',
    [['Uᵢ₋₁', '前 i−1 步累计约束实例。'], ['uᵢ', '第 i 个里程碑的局部状态转换约束。'], ['rᵢ', 'Fiat–Shamir 挑战或验证者随机挑战。']],
    [['Encode local step', '把 prevCommitment、nextCommitment、规则和回执写成关系 uᵢ。'], ['Fold with challenge', '用不可预测挑战把旧实例和新实例线性组合，作弊误差随域大小受限。'], ['Compress at finality', '任务结束时对累计实例生成一次递归或 SNARK 证明，链上验证成本不随步数线性增长。']],
    'VerifyRecursive(vk,C₀,Cₙ,ruleHash,πrec)=1',
    '最终证明绑定起点、终点和规则，且每次折叠关系满足时，才代表全部里程碑连续有效。',
    '折叠方案与最终证明系统满足可靠性；挑战通过正确域分离的 Fiat–Shamir 生成。',
  ),
  poi: derive(
    'ValidPoI = Dsig ∧ Raccept ∧ VerifyExec(πexec)=1 ∧ taskKey∉Spent',
    [['Dsig', '真实需求方对目标、预算、SLA 与 nonce 的签名。'], ['Raccept', '按预先冻结规则得到的 Validator 验收裁决。'], ['πexec', '绑定代码、输入、输出和环境的执行证明。']],
    [['Prove demand', '需求方签名证明任务不是执行者自造，并冻结验收口径。'], ['Prove useful result', '独立 Validator 或密码学谓词确认结果满足需求，而非仅证明消耗了算力。'], ['Prove execution & uniqueness', '执行证据绑定实际工作轨迹，Spent 集合保证同一任务只计一次。']],
    'VerifyDemand=1 ∧ VerifyAcceptance=1 ∧ VerifyExec=1 ∧ Fresh(taskKey)=1',
    '四项同时通过时，PoI 才证明“一次由真实需求触发、产出被接受、执行可核验且未重复计数的工作”。',
    '验收规则能代表真实效用；需求方与 Validator 的串谋由押金、抽检、挑战或多方阈值控制。',
  ),
  vrfBft: derive(
    '(y,πvrf)=VRF_sk(epoch∥poiRoot); proposer = argmin(yᵢ/weightᵢ); finality requires Q votes',
    [['y/πvrf', '不可预先操纵且可公开验证的随机输出与证明。'], ['weightᵢ', '由有效 PoI 或治理规则得到的有界提议权重。'], ['Q', 'BFT 最终确认法定人数。']],
    [['Freeze seed', '先由已最终确认 epoch 和 poiRoot 决定抽签输入，候选人不能事后换种子。'], ['Private evaluate, public verify', '每个候选人本地计算 VRF；网络用公钥验证输出确由该密钥产生。'], ['Separate proposal from finality', 'VRF 只选择提议者，区块仍须经 BFT 的 Q 个有效签名才最终确认。']],
    'VRFVerify(pk,seed,y,πvrf)=1 ∧ Eligible(y,weight)=1 ∧ |votes(block)|≥Q',
    '抽签证明、资格权重和 BFT 证书三项都有效时，区块才能进入最终状态。',
    'VRF 密钥已注册；PoI 权重有上限和反女巫约束；随机种子不可被单方回滚操纵。',
  ),
  eventLog: derive(
    'eventId=H("event"∥chainId∥height∥txIndex∥taskId∥stage∥payloadRoot)',
    [['height/txIndex', '事件在已确认账本中的唯一位置。'], ['taskId/stage', '所属任务和生命周期阶段。'], ['payloadRoot', '事件正文或回执包的内容承诺。']],
    [['Canonical event', '部署、调用、执行、验收、拒绝和结算使用统一字段与类型编号。'], ['Bind ledger position', '把链、区块高度和交易序号写入 ID，避免索引器把同名事件混淆。'], ['Index by task', '观察器按 taskId 和前序根重建轨迹，再与状态根和包含证明交叉核验。']],
    'MerkleVerify(block.eventRoot,eventId,path)=1 ∧ event.prevRoot=expectedRoot',
    '事件被区块承诺且前序根连续时，审计者可以确定它的顺序、归属和内容未被替换。',
    '目标链提供不可篡改的最终事件根；链重组深度由适配器最终性规则明确处理。',
  ),
  semanticAdapter: derive(
    'Preserve(F) ⇔ Decode_target(Encode_target(F(x))) = F(x) for Identity, Event, State, Proof',
    [['F', 'ACVM 的身份、事件、状态或证明语义。'], ['Encode_target', '写入目标链账户、存储、日志或验证器的适配编码。'], ['Decode_target', '从目标链读取并恢复 ACVM 规范对象。']],
    [['Define invariant', '先写明跨链前后必须保持的主体、顺序、状态根和公共输入。'], ['Round-trip test', '规范对象编码到目标链格式再解码，结果必须逐字段相等。'], ['Finality mapping', '只有目标链达到配置的最终性条件，适配器才把结果标记为 ACVM 已确认。']],
    'Canonical(F(x)) = Canonical(Decode_target(Encode_target(F(x))))',
    '往返编码不丢字段、不改顺序，并且目标链最终性已满足时，适配没有改变 ACVM 语义。',
    '目标链接口、事件排序和证明验证能力被版本化；升级时必须重新跑兼容性向量。',
  ),
  mechanismDesign: derive(
    'Uhonest = paccept·R − Chonest;  Udeviate = ppass·R − Cdeviate − pdetect·Slash;  IC ⇔ Uhonest ≥ Udeviate',
    [['R', '结果通过验收后获得的服务费与信誉收益。'], ['C', '诚实服务或偏离策略分别承担的真实成本。'], ['pdetect/Slash', '偏离被发现的概率与保证金、信誉惩罚。']],
    [['Pay for accepted outcome', '奖励只绑定已验收结果，不按调用次数、Token 或自报工作量支付。'], ['Price deviation', '把抽检、挑战和多方验证转成 pdetect，并让可执行惩罚进入偏离收益。'], ['Check incentive compatibility', '逐类比较诚实策略和可行偏离；只有诚实效用不低于任何偏离，机制才有激励相容性。']],
    '∀ deviation d: paccept·R−Chonest ≥ ppass(d)·R−Cd−pdetect(d)·Slash',
    '参与者在理性逐利假设下没有通过伪造、偷工减料或重复申报获得更高期望收益时，奖励结构成立。',
    '参与者近似风险中性且能执行惩罚；验收与检测不能被同一方廉价串谋，R 和 Slash 需按任务价值校准。',
  ),
  informationDesign: derive(
    'Brier(q,o)=−(q−o)²;  E[Brier(q,o)]=−(q−p)²−p(1−p), maximized at q=p',
    [['p', '服务成功的真实主观概率。'], ['q', 'Agent 对外报告的成功概率或置信度。'], ['o∈{0,1}', '任务最终是否通过验收。']],
    [['Publish decision signal', '公开能力域、价格、有效期、任务难度和可验证历史，不公开无关隐私。'], ['Score after outcome', '任务终局后用严格适当评分规则比较 q 与真实结果 o。'], ['Update domain reputation', '按能力域、难度和时间衰减累计得分，避免低价值任务刷高全部能力。']],
    'dE[Brier(q,o)]/dq = −2(q−p)=0 ⇒ q=p;  d²/dq²=−2<0',
    '期望得分在如实报告 q=p 时唯一最大，因此理性 Agent 没有夸大或压低成功概率的收益。',
    '结果 o 可被可靠验收；任务选择偏差和串谋需单独校正；信誉只作为信号，不能替代本次执行证明。',
  ),
} as const;
