import type { ScreenId } from './deck';

export type SpeakerGuideEntry = {
  duration: string;
  focus: string;
  connection: string;
  opening: string;
  beats: readonly [string, string, ...string[]];
  transition: string;
};

export const speakerGuides = {
  top: {
    duration: '0:15',
    focus: 'ACVM：让 AI 服务按已验证结果付费。',
    connection: '先给产品结论，下一页再解释它改了什么。',
    opening: 'ACVM，让 AI 服务按已验证结果付费。',
    beats: ['只读产品名和标语。', '停一拍，让听众先记住“已验证结果”。'],
    transition: '要做到这一点，ACVM 改了两件事。',
  },
  'product-thesis': {
    duration: '0:55',
    focus: '把客户需要的模型推理，变成可付款、可记账的有效工作。',
    connection: '两项替换最终落在同一笔 AI 订单上。',
    opening: 'ACVM 做两项替换：用有业务价值的推理替代空耗算力，用智能体合约管理链下长任务。',
    beats: ['客户先签结果目标，调用量只计成本，不直接触发付款。', 'Worker 交付结果，Validator 独立验收；通过后才生成 ValidPoI。', '同一份 ValidPoI 先用于结算，网络成熟后再用于贡献计权。'],
    transition: '先看最关键的一步：什么条件才能放款。',
  },
  'product-snapshot': {
    duration: '1:05',
    focus: '调用成功只说明服务发生过，验收通过才说明结果可交付。',
    connection: 'ACVM 把目标、证据、裁决和资金状态连成一个闭环。',
    opening: '接口返回 200，不等于客户拿到了结果。ACVM 先锁定达标条件，再决定是否付款。',
    beats: ['任务规则写清目标、门槛、预算、权限和截止时间。', 'A3S 保存产物、外部观测和运行回执，执行后不能换口径。', 'Validator 给出通过、拒绝或挑战裁决；只有通过才生成 PoI 并放款。'],
    transition: 'GEO 是最容易看懂这套付款逻辑的业务。',
  },
  'geo-verification': {
    duration: '1:35',
    focus: 'GEO 按独立观测到的引用增量结算，不按内容产量结算。',
    connection: '真实需求、链下推理、外部证据和结果付款在这一单里同时出现。',
    opening: '品牌方买的不是文章数量，而是生成式搜索里的引用增长。',
    beats: ['签约时冻结问题集、目标引擎、站点版本、基线、观察窗口和增量门槛。', 'GEO Worker 做优化，独立观察节点按同一口径复测，不能由服务方自己打分。', '增量达标且挑战期结束后，ACVM 生成 ValidPoI，底层链释放结果费。'],
    transition: '如果数据不能公开，付款逻辑不变，证据路径要换。',
  },
  simulation: {
    duration: '1:35',
    focus: '个体数据留在本地，客户拿到可复核的群体统计。',
    connection: '它沿用 GEO 的订单闭环，但把公开观测换成隔离执行和安全聚合。',
    opening: '社会模拟最难的不是多跑 Agent，而是既不能泄露个人轨迹，也不能只交一张成绩单。',
    beats: ['合约先锁定模型版本、样本承诺、随机种子、隐私预算和统计口径。', '雾节点在数据所在地运行；离开隔离域的只有聚合结果、置信区间和证明。', 'Validator 复核统计管线与重复实验；协议证明按约定运行，不替模型假设背书。'],
    transition: '两个场景都能交付结果，但为什么进入 ACVM 后必须有 PoI？',
  },
  'geo-poi-boundary': {
    duration: '1:20',
    focus: 'GEO 可以不用 PoI；选择 ACVM，就必须由 ValidPoI 触发结果费。',
    connection: 'PoI 不是 GEO 成立的前提，而是 ACVM 把结果变成协议资产的关键。',
    opening: '先正面回答：GEO 离开 PoI 也能做，中心化审计就能交付；但那不是 ACVM。',
    beats: ['两种方案都要冻结问题集、基线、观察窗口和增量门槛。', 'ACVM 再把 SignedDemand、执行回执、AcceptedResult 和唯一 taskKey 合成 ValidPoI。', 'ValidPoI 先解锁结果费；开放网络阶段再进入激励和提议权重。'],
    transition: 'PoI 的位置明确后，再比较其他 AI 网络到底在证明什么。',
  },
  'useful-work': {
    duration: '1:45',
    focus: '相对质量、执行忠实、经济安全和业务达标，是不同的验证命题。',
    connection: 'ACVM 不取代现有网络，而是补上签名订单到业务结算这一段。',
    opening: '比较 PoI，先比较系统最终判断真假的条件，而不是先比较名字。',
    beats: ['Bittensor、Allora 主要聚合相对质量；Gensyn Verde、EigenAI 主要验证执行忠实。', 'EigenLayer 提供可罚没的经济安全；ChainOpera 计量数据、模型、计算和 Agent 的广义贡献。', 'ACVM 接收这些能力，但最终判断的是：签名订单约定的业务结果是否达标。'],
    transition: '要做任务级裁决，先解释模型为什么不能让全网重跑。',
  },
  'execution-boundary': {
    duration: '1:25',
    focus: 'Worker 执行一次，共识节点验证回执和确定性状态变化。',
    connection: 'ACVM 把非确定执行留在链下，把可重复验证的规则留在共识边界内。',
    opening: '链上虚拟机靠全网重放获得一致性；模型推理和 Agent 工具调用不具备这个条件。',
    beats: ['私有数据不能复制给所有节点，GPU 算子和采样也未必逐字一致。', '邮件、订单、支付等工具有副作用，不能让每个节点重复执行。', '因此 Worker 只执行一次，节点检查签名、承诺、证明、裁决和状态转换。'],
    transition: '把执行边界放回一笔订单，就得到 ACVM 的完整工作流。',
  },
  'system-architecture': {
    duration: '1:45',
    focus: 'AP2 管授权，A3S 管执行，ACVM 管验收与 PoI，现有链管终局。',
    connection: '四层用同一个 taskId、contractRoot 和回执根衔接，各自只负责一层。',
    opening: '这不是再造一套全栈协议，而是把已有能力按责任边界接起来。',
    beats: ['AP2 的 Intent 或 Cart Mandate 绑定主体与支付授权，ACVM 补充结果条件。', 'A3S Flow、Runtime、Box、Power、Event 和 Sentry 执行任务并形成运行回执。', 'ACVM Validator 检查运行证据和业务证据，生成 ValidPoI；现有链或 AVS 提供终局与经济安全。'],
    transition: '订单的第一步不是执行，而是先找到合适的 Agent。',
  },
  ans: {
    duration: '1:20',
    focus: 'ANS 把名称解析成带签名、可核验的智能体服务卡。',
    connection: '调用方核验服务卡后，再通过 A2A 签下同一个 taskId。',
    opening: '钱包地址只能回答“是谁”，不能回答“会做什么、多少钱、由谁验收”。',
    beats: ['服务卡包含 DID、A2A 端点、能力版本、价格、有效期和推荐 Validator 集。', '信誉按能力和任务类型分别统计，并带样本量，避免小任务刷出全局高分。', 'ANS 负责发现，不替代信任判断；调用方仍要查签名、撤销状态和历史回执。'],
    transition: '找到 Agent 后，还要用一份合约管住预算、权限和失败。',
  },
  'agentic-contract': {
    duration: '1:20',
    focus: '智能体合约把跨区块 AI 任务写成由签名回执推进的状态机。',
    connection: '它固定 Worker、Validator 和结算接口，避免任务执行后换规则。',
    opening: '普通智能合约适合确定性交易；AI 任务会调用外部工具、等待审批，也可能超时和被挑战。',
    beats: ['Schema 定义输入、结果、证据和裁决格式，Worker 与 Validator 使用不同入口。', 'Settlement 写清通过、拒绝、超时、挑战和罚没怎样改变资金状态。', '目录生成 contractRoot；任务引用固定版本，规则变化必须发布新版本。'],
    transition: '规则锁定后，任务可以被调度到靠近数据的位置。',
  },
  'fog-inference': {
    duration: '1:25',
    focus: '数据在现场处理，结果根和运行证明进入全网核验。',
    connection: 'ANS 给候选 Worker，智能体合约给调度条件，ACVM 保存回执与裁决。',
    opening: '医疗、制造和政务数据通常不能先搬到中心云，再谈验证。',
    beats: ['ACVM 按地域、延迟、硬件证明和价格选择附近的雾节点。', 'a3s-box 隔离工作负载，a3s-power 运行模型，原始数据不出域。', 'Worker 提交结果根和运行证明；Validator 验回执，共识节点不重跑模型。'],
    transition: '运行回执只能说明任务怎么跑，还不能说明业务结果是否达标。',
  },
  'verification-engine': {
    duration: '1:35',
    focus: '运行证明回答“怎么跑”，业务证据回答“是否达标”。',
    connection: '智能体合约在执行前选定证据组合，并公开成本和剩余信任。',
    opening: 'TEE 能证明程序在可信环境中运行，却不能证明 GEO 引用真的增长。',
    beats: ['确定性小任务可独立复算；高成本任务可乐观提交、抽检并接受挑战。', 'TEE 证明隔离环境，零知识证明验证预定义关系，两者都不自动判断开放式质量。', 'GEO 用冻结观测源和增量门槛验结果；社会模拟还要检查样本、随机过程和统计管线。'],
    transition: '裁决通过以后，才能把这次服务铸成唯一的 PoI。',
  },
  'poi-proof': {
    duration: '1:25',
    focus: 'PoI 只记录有真实需求、结果达标、执行可查且不能重放的服务。',
    connection: '四项条件都绑定同一个 taskId，缺一项就不能结算。',
    opening: 'GPU 使用证明只能说明消耗过算力，不能说明客户需要它，也不能说明结果可用。',
    beats: ['SignedDemand 证明真实订单并锁定预算与 nonce。', 'AcceptedResult 证明验收通过；ExecutionEvidence 绑定模型、输入、输出和运行环境。', 'taskKey 先写入已使用集合，再生成 ValidPoI；同一结果不能重复领取费用。'],
    transition: 'ValidPoI 可以结算，但还不能直接决定谁记账。',
  },
  'poi-consensus': {
    duration: '1:30',
    focus: 'PoI 只增加被抽中的概率，不能单方面取得终局。',
    connection: '归一、封顶和衰减控制权重，VRF 选提议者，BFT 或底层链确认终局。',
    opening: '如果推理做得多就直接拥有记账权，大客户和刷单者很快会控制网络。',
    beats: ['PoI 按任务类型归一，再乘质量系数和时间衰减，并设置主体上限。', '候选者用 epoch 和 poiRoot 运行 VRF；权重越高，抽中概率越高，但不能预选结果。', '获选者只能提议区块；其他节点验 PoI、交易和状态，达到法定人数才终局。'],
    transition: '技术路径讲完，接着看一笔订单里的钱和责任。',
  },
  'economy-roles': {
    duration: '1:35',
    focus: '结果费、验证成本和违规保证金分开结算，正常失败不等于作弊。',
    connection: '三种结局把需求方、Worker、证据方、Validator 和挑战者的得失说清楚。',
    opening: '用一笔 12 万元托管订单说明：10 万是结果费，其余是证据、验证、链上费用和挑战准备金。',
    beats: ['验收通过：Worker 拿结果费，证据方、Validator 和协议拿已完成工作的费用。', '正常未达标：结果费退回，Worker 不得结果费但不罚保证金，验证成本照常支付。', '证明造假：结果费退回，Worker 保证金被罚；有效挑战者和安全储备分享罚没资金。'],
    transition: '钱分清后，再看 ACVM 怎样接入现有基础设施。',
  },
  'deployment-modes': {
    duration: '1:50',
    focus: 'A3S 和 ACVM 保持不变，身份、支付与终局按目标基础设施适配。',
    connection: '国内产业链与 EigenLayer 分开接入，ACVM 不替代现有基础设施。',
    opening: '国内并不存在一个统一接口的“国家链”，所以接入方案必须拆开说。',
    beats: ['国内模式沿用 CA、BID 或 DID、国密和权限治理，只把 taskRoot、poiRoot 与资金状态上链。', '人民币托管仍走合规支付系统；Prompt、原始数据和详细证据留在 A3S 证据存储。', '开放模式可把 Validator 接成 EigenLayer AVS Operator Set；AVS 提供经济安全，ACVM 仍定义业务判定。'],
    transition: '接口能接上还不够，刷单、重放和串谋必须逐条处理。',
  },
  'security-boundaries': {
    duration: '1:30',
    focus: '每条主要作弊路径都有独立控制，不把安全押在一个信誉分上。',
    connection: '这些控制直接变成试点指标，而不是停留在原则描述。',
    opening: 'PoI 最现实的攻击，不是破解密码学，而是把自买自卖的垃圾任务包装成有效工作。',
    beats: ['身份关联、预算门槛和主体封顶降低自交易刷单收益。', 'taskKey、输出根和 epoch 防重放；抽样复算、TEE 与业务验收控制伪造。', '随机 Validator 委员会、利益冲突限制、保证金和挑战奖励提高串谋成本。'],
    transition: '部署边界和攻击面明确后，最后只看第一项交付。',
  },
  'product-roadmap': {
    duration: '1:15',
    focus: '基于 A3S 跑通一笔从签约、ValidPoI 到结果付款的真实任务。',
    connection: 'PoI 从第一天生成，但先影子运行，再接小额结算，最后才影响提议权。',
    opening: 'ACVM 目前是产品规范和演示，不是生产网络；下一步只需要把一笔真实订单跑到底。',
    beats: ['先在 A3S 上实现任务适配、回执绑定、ACVM 状态机和 shadow PoI。', '选 GEO 或社会模拟做试点，接入真实需求方、Worker、证据源和 Validator。', '结算与攻击数据达标后，再把累计 PoI 接入 VRF、BFT 或 EigenLayer AVS。'],
    transition: '首个验收标准很具体：客户知道为何付款，服务方能证明为何得款，评审可以重建整条裁决链。',
  },
} as const satisfies Record<ScreenId, SpeakerGuideEntry>;
