import type { ScreenId } from './deck';

export type SpeakerGuideEntry = {
  duration: string;
  focus: string;
  connection: string;
  opening: string;
  beats: readonly [string, string, ...string[]];
  transition: string;
};

export const speakerGuides = {
  top: {
    duration: '1:00',
    focus: 'ACVM 让一次模型推理同时创造客户服务价值与区块链共识价值。',
    connection: 'PoI 替换无外部价值的哈希工作来源，Agentic Contract 替换不适合异步 AI 任务的智能合约。',
    opening: '区块链一直在花钱证明“有人做了工作”，AI 网络则在花钱完成真正的模型推理。ACVM 把这两笔成本合成一笔。',
    beats: ['真实需求触发模型推理，结果通过独立验收后才生成 Proof of Intelligence。', '智能体合约管理身份、预算、外部工具、回执、挑战和结算，不要求所有节点重跑模型。', '有效 PoI 形成有上限的候选权重，VRF 选择提议者，BFT 或底层链规则完成终局。'],
    transition: '先用一页产品图和两个场景把这套替换说具体。',
  },
  'product-snapshot': {
    duration: '1:30',
    focus: 'ACVM 的产品定义由两项替换和一个统一闭环组成。',
    connection: 'PoI 解决有效计算怎样进入共识，Agentic Contract 解决 AI 任务怎样进入状态与结算。',
    opening: 'ACVM 不是给现有区块链再加一个 AI 接口，它同时改变“什么算工作”和“什么算合约”。',
    beats: ['第一项替换：哈希工作只证明资源消耗；PoI 还要求真实需求、执行证据和结果验收。', '第二项替换：EVM 合约适合确定性交易；Agentic Contract 管理跨区块、跨工具、可争议的智能体任务。', '两者共用 taskId、回执与最终状态，因此一次服务既能结算业务价值，也能积累网络贡献。'],
    transition: '先看 ACVM 最容易被客户理解的第一项服务：GEO 结果验证。',
  },
  'geo-verification': {
    duration: '2:00',
    focus: 'GEO 把一项真实模型服务从自报成绩变成可验收的 PoI。',
    connection: '真实品牌需求、优化执行、独立观测和最终裁决正好构成 PoI 的四类证据。',
    opening: '品牌方不为“生成了多少内容”买单，它为生成式搜索里可独立观测的引用增量买单。',
    beats: ['开始前冻结问题集、引擎、基线、观察窗口和增量门槛，避免执行后换评分口径。', 'GEO Worker 使用模型和工具优化内容，独立观察节点用相同问题集复测，执行与评分不能由一方控制。', 'Validator 验收有效增量；通过挑战期后既释放结果奖励，也产生绑定本次真实需求的有效 PoI。'],
    transition: '第二项场景把难度再提高：原始数据不能公开，推理贡献仍要能证明。',
  },
  simulation: {
    duration: '2:00',
    focus: '社会模拟证明私有推理也可以形成可验证结果与网络贡献。',
    connection: 'PoI 不要求公开敏感输入，只要求公开足以核验需求、执行、验收和唯一性的证据。',
    opening: '社会模拟真正的矛盾是：个人画像和轨迹不能外泄，研究方又不能只说“相信我的结论”。',
    beats: ['模型版本、样本承诺、随机种子和隐私预算先写入智能体合约。', '推理在隔离域运行，个体轨迹不出域；安全聚合只输出群体指标、置信区间和执行度量。', '独立节点复核统计管线与重复实验。协议能证明按约定过程运行，不能把模型假设包装成现实真相。'],
    transition: '两个场景说明产品有用，下面从第一性原理解释为什么要替换 PoW 的工作来源。',
  },
  'useful-work': {
    duration: '1:50',
    focus: '共识需要稀缺成本、公开提议和终局，不需要成本一定来自无意义哈希。',
    connection: 'ACVM 只替换提议权的工作量来源，保留随机选择、区块验证和多数最终确认。',
    opening: '先把 PoW 的安全功能与它采用的哈希函数分开。真正需要的是抗女巫，不是 nonce 本身。',
    beats: ['稀缺投入让身份无法零成本复制；公开规则选择下一位区块提议者；冲突区块还要有收敛与最终性。', '哈希竞争满足前两项，却几乎不产生链外价值。它是安全成本，不是客户可消费的服务。', 'ACVM 用已验收的模型推理作为候选贡献来源；VRF 与 BFT 仍分别承担随机选择和终局。'],
    transition: '工作来源可以替换，但 AI 任务还无法塞进传统虚拟机；第二个第一性问题来自执行模型。',
  },
  'execution-boundary': {
    duration: '2:00',
    focus: 'EVM 通过全网确定性重放建立共识，智能体任务无法按这个方式运行。',
    connection: 'ACVM 把模型和工具放在链下执行，把可确定验证的回执与状态转换留在共识边界内。',
    opening: 'EVM 的可靠来自所有节点做同一道题；AI 任务往往连题目所需的数据和环境都不能公开。',
    beats: ['模型采样、GPU 算子和外部网页可能产生差异；私有数据也不能复制给每个节点。', '发邮件、下订单、调用第三方 API 等副作用不能被全网重复，长任务还会跨越多个区块。', '因此 ACVM 采用一次执行、多种验证：节点检查签名、承诺、证明、裁决和状态转换，而不是重跑完整任务。'],
    transition: '两个边界明确后，可以画出 ACVM 的双引擎产品架构。',
  },
  'system-architecture': {
    duration: '1:40',
    focus: '同一个 AcceptedResult 同时进入结算支路和 PoI 贡献支路。',
    connection: 'Agentic Contract 管任务，PoI 引擎管有效贡献；两者共享需求、执行和验收证据。',
    opening: 'ACVM 不会为共识再制造一份计算，它复用已经为客户完成的模型推理。',
    beats: ['需求方签名任务，智能体合约冻结预算与状态，Worker 完成推理并提交执行回执。', 'Validator 按事前规则验收输出，AcceptedResult 成为两个支路的共同输入。', '业务支路走挑战与结算；共识支路再检查防重放，生成 PoI 并进入候选贡献池。'],
    transition: '先拆 PoI：一份模型推理凭什么被认定为有效工作。',
  },
  'poi-proof': {
    duration: '1:50',
    focus: 'PoI 证明的是有效服务，不是单纯算力消耗，也不是模型智力评分。',
    connection: '四项条件把需求、执行、结果和唯一性绑定到同一个 taskId。',
    opening: '只提交一张 GPU 使用证明远远不够，那仍然可能是自造任务、垃圾结果或重复计分。',
    beats: ['SignedDemand 证明任务来自真实需求方，并冻结目标、预算、SLA 与 nonce。', 'AcceptedResult 证明结果通过预定验收；AttestedExecution 绑定模型、输入、输出和运行环境。', 'AntiReplay 把 taskKey 写入已使用集合。任何一项失败，任务可以留下回执，但不能形成有效 PoI。'],
    transition: '有效 PoI 进入池后，还要回答它怎样影响记账权，而不让大户直接控制账本。',
  },
  'poi-consensus': {
    duration: '2:00',
    focus: 'PoI 提供有界提议权重，VRF 负责抽签，BFT 负责最终确认。',
    connection: '这条分工让“有用工作替换哈希工作”成立，同时避免把 PoI 误当成完整共识。',
    opening: '所谓记账权要拆成两件事：谁有机会提议，其他节点为什么接受并最终确认。',
    beats: ['有效 PoI 先按任务类型归一，经过质量系数、时间衰减和单主体封顶，得到 boundedWeight。', '每个候选者用 epoch 与 poiRoot 计算 VRF；输出除以权重后比较，结果可公开验证且无法提前挑选种子。', '获选者只能提出候选区块。其他节点仍重验 PoI、交易和状态转换，达到 BFT 法定人数后才终局。'],
    transition: '共识贡献有了来源，应用层还需要一种能承载真实 Agent 工作的合约。',
  },
  'agentic-evolution': {
    duration: '1:30',
    focus: 'Agentic Contract 把异步智能体工作建模为可验证状态机。',
    connection: '它在 EVM 确定性代码之外，增加身份、预算、外部工具、回执、验收和跨区块生命周期。',
    opening: '智能合约擅长在一笔交易里改状态，智能体合约要管理一项可能运行几小时、调用多个系统的任务。',
    beats: ['任务可以经历 Requested、Assigned、Running、Submitted、Accepted 与 Settled 等阶段。', '状态不是由 Worker 自报推进，而是由签名回执、证明或 Validator 裁决触发。', '预算守恒、能力只能收窄、回执连续和防重放是跨阶段不变量。'],
    transition: '状态机只是外观，真正能被部署的是一份有版本的智能体合约对象。',
  },
  'agentic-contract': {
    duration: '1:30',
    focus: 'Agentic Contract 同时版本化输入输出、执行接口、验收接口和结算条件。',
    connection: 'contractRoot 保证 Worker 与 Validator 使用同一份业务规则，任务中途不能偷换版本。',
    opening: '传统智能合约只固定链上代码，智能体合约还必须固定链下执行与验收之间的接口。',
    beats: ['Schema 定义任务输入、结果、证据和裁决格式；Worker 入口描述执行，Validator 入口描述验收。', 'Settlement 写明通过、拒绝、挑战、超时和罚没分别怎样改变资金状态。', '目录规范编码后生成 contractRoot，taskId 引用该根；任何文件变化都会成为新版本。'],
    transition: '把 PoI 和智能体合约接起来，看一项真实任务怎样走完整闭环。',
  },
  'task-lifecycle': {
    duration: '1:40',
    focus: '一个 taskId 串起服务交付、PoI 生成、共识确认和结果结算。',
    connection: '这六个事件是两个场景、经济模型和后续网络扩展的共同最小单元。',
    opening: 'ACVM 不记录模型每个 token，它只记录会改变任务责任、共识权重或资金状态的事件。',
    beats: ['真实需求先签名，智能体合约冻结角色与规则；Worker 完成模型推理并提交执行回执。', 'Validator 验收结果，PoI 引擎检查需求、执行、验收和防重放。', '有效 PoI 进入共识流程；区块终局后，贡献被记录，业务结果也只能结算一次。'],
    transition: '完整流程成立的前提，是模型结果能以可接受的成本被验证。',
  },
  'verification-engine': {
    duration: '1:50',
    focus: '不同任务用不同验证组合，不存在一种证明自动覆盖所有 AI 质量。',
    connection: 'PoI 把验证策略与剩余信任写进 Agentic Contract，避免执行后才决定怎样验收。',
    opening: '“可验证 AI”不是单一技术。复算、挑战、TEE、零知识和业务验收证明的是不同命题。',
    beats: ['可确定的小任务可以独立复算；高成本任务可以乐观提交并接受抽检和挑战。', 'TEE 证明特定代码在隔离环境运行，zkML 证明电路关系成立，但都不自动证明业务目标正确。', 'GEO 等外部效果仍要依赖冻结观测源与验收谓词，协议必须公开成本和剩余信任。'],
    transition: '当输入属于个人或企业，验证还要在不公开原始数据的条件下完成。',
  },
  'private-evidence': {
    duration: '1:30',
    focus: '隐私输入留在业务域，承诺、执行度量和证明进入协议。',
    connection: '这使私有模型推理可以生成 PoI，而不是要求所有数据上链。',
    opening: '隐私执行的关键不是把一切藏起来，而是藏起来以后仍能证明运行了约定的任务。',
    beats: ['输入先生成承诺，隔离环境加载对应数据和模型；执行度量绑定代码与硬件环境。', '结果根、聚合指标或零知识证明离开私有域，原始文档、Prompt 和轨迹仍由数据所有方控制。', '链上只保留核验状态和 PoI 所需的公共输入，审计权可以与公开读取权分开。'],
    transition: '这些能力不要求一开始就建设独立公链，可以从现有系统旁边逐步部署。',
  },
  'deployment-modes': {
    duration: '1:30',
    focus: 'ACVM 可以按协处理器、原生执行器、应用链三种模式演进。',
    connection: '产品先复用现有链的成员、P2P、账本与最终性，再逐步引入 PoI 权重和专用执行。',
    opening: '技术可行性的第一条原则，是不要把“先造一条新链”当成试点前提。',
    beats: ['协处理器模式只提交任务回执和证明，现有联盟链继续负责共识与托管，适合首个试点。', '原生执行器模式让链节点直接验证 Agentic Contract 状态转换，但模型仍在专门 Worker 上执行。', '只有任务规模和开放参与需求足够大时，才建设带 PoI 权重、VRF 与 BFT 的 ACVM 应用链。'],
    transition: '部署路径可控以后，还要正面列出最容易破坏 PoI 的五类攻击。',
  },
  'security-boundaries': {
    duration: '1:50',
    focus: 'PoI 的可行性取决于防刷、防重放、可验收与反串谋控制。',
    connection: '每个安全控制都对应一种可观测指标，才能在试点里被验证和调参。',
    opening: '有用工作证明最危险的攻击不是破解哈希，而是把无价值任务伪装成真实需求。',
    beats: ['签名和托管仍挡不住自交易，因此要做关联身份分析、任务价值门槛和单主体权重封顶。', 'taskKey、输出根与 epoch 防止同一结果重复计分；抽样复算、TEE 或业务验收防止伪造执行。', '随机 Validator 委员会、利益冲突限制、保证金和挑战奖励降低串谋收益；任务难度则必须分类归一。'],
    transition: '安全控制会产生成本，经济模型要说明谁付费、谁受益、谁为作弊买单。',
  },
  'economy-roles': {
    duration: '1:50',
    focus: '需求、执行、证据、验收、挑战和终局是六类独立贡献。',
    connection: '角色可以由同一机构兼任，但授权、收入、权重和责任必须分别记账。',
    opening: '经济模型先不谈币价，先回答每个人做了什么、拿到什么、做错会失去什么。',
    beats: ['需求方签名真实任务并托管预算；Worker 投入模型、工具和算力，交付可验收结果。', '证据方和 Validator 完成独立验证，挑战者提供反证，共识节点完成排序和最终确认。', 'Worker 不能控制全部证据和 Validator；否则业务付款与 PoI 权重都会被同一利益方操纵。'],
    transition: '把六类角色放进两条价值流，区分客户的钱和网络的奖励。',
  },
  'useful-compute-economy': {
    duration: '1:50',
    focus: '业务结果费与网络共识奖励分账，同一份计算不能重复虚构收入。',
    connection: '客户预算购买结果；PoI 只提供候选权重，节点完成提议和确认后才获得网络费用。',
    opening: 'ACVM 有两条价值流，但不是同一项模型调用收两遍钱。',
    beats: ['业务市场中，验收终局后 Worker 获得结果奖励，证据方和 Validator 获得各自服务费，协议收取结算费用。', '网络侧，有效 PoI 经过归一与封顶后提高提议概率；只有实际履行提议、验证或确认职责者获得配置的网络奖励。', '造假触发罚没并奖励有效挑战。是否发行原生资产、费率与奖励曲线仍属于待试点参数，不能在产品页伪装成定案。'],
    transition: '经济闭环只在真实数据里才算成立，因此落地顺序从最小可运行内核开始。',
  },
  'product-roadmap': {
    duration: '1:30',
    focus: 'ACVM 当前是概念规范与产品演示，下一里程碑是一项真实任务的 Finalized PoI。',
    connection: '路线依次验证合约对象、PoI 有效性、场景结果和开放共识，不跳过中间证据。',
    opening: '这里必须把产品愿景与当前成熟度分开说清楚。',
    beats: ['今天已经形成 PoI、Agentic Contract、验证边界和经济模型的可讨论规范，但不是生产网络。', '下一步交付 Contract SDK、本地任务运行器和 PoI 验证器，跑通 SignedDemand 到 ValidPoI。', 'GEO 与社会模拟试点验证真实需求和结果；指标稳定后，再实现有界权重、VRF、BFT 与多链适配。'],
    transition: '要启动首个试点，只需把六项输入定义清楚，不必先完成整张网络。',
  },
  'pilot-cta': {
    duration: '1:10',
    focus: '首个试点要同时验证真实需求、模型服务、结果验收、执行证明、共识权重和资金结算。',
    connection: '这六项输入把 ACVM 的两项替换收敛成一个可测量闭环。',
    opening: '判断一个业务是否适合 ACVM，不先问用哪条链，先问这六个问题能不能得到明确答案。',
    beats: ['谁签名真实任务，哪项模型推理创造客户价值，什么条件代表结果达标？', '怎样绑定模型、输入、输出和执行环境，谁负责独立验证与挑战？', 'PoI 怎样归一和封顶，终局后结果奖励、网络费用与罚没分别流向谁？'],
    transition: 'ACVM 的一句话结论：把真实模型推理变成可验证工作，再用智能体合约把它带入共识与结算。',
  },
} as const satisfies Record<ScreenId, SpeakerGuideEntry>;
